### PR TITLE
Create parse_negative_zero_as_int cfg flag

### PR DESCRIPTION
**Pull request by Maximus-**
Introduce cfg!(parse_negative_zero_as_int) to create a build-time option to parse -0 the same as other JSON parsers.

### CODE REVIEW

**Review by djmitche — CHANGES_REQUESTED** [review]
This will need updated tests in `tests/test.rs`, and also an addition to `.github/workflows/ci.yml` to test with this feature enabled.

**Comment by Maximus-** [comment]
Ack, will do. :)

**Comment by Maximus-** [comment]
Done, let me know how it looks :)

**Review by djmitche — APPROVED** [review]
Nice, thanks!

**Pull request merged**
